spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: "db.migration"
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  graphql:
    graphiql:
      enabled: true
    cors:
      allow-credentials: true
      allowed-origin-patterns: "*"

spring-docs:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
